/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Mastermind.y;

public class CInfoJuego{
    public boolean someLibraryMethod() {
        return true;
    }
    
    public String[] comprobaciones(String[] arrayUsuario, String[] arrayGanador)
    {
    	String[] result = {};
    	
    	//IMPLEMENTACIÓN
    	for (int i = 0; i < arrayUsuario.length; i++)
    	{
    		if (arrayUsuario[i] == arrayGanador[i])
    		{
    			result[i] = "negra";
    		}
    	  	else
    	  	{
    	  		if (colorExiste(arrayUsuario[i], arrayGanador))
    	  			result[i] = "blanca";
	  			else
	  				result[i] = "null";
    	  	}
    	}
    	String[] expectedResult = {"negra","negra","negra","negra","negra"};
    	System.out.println("expected: " + expectedResult);
    	System.out.println("result: " + result);
    	
    	return result;
    }
    
    public boolean colorExiste(String color, String[] arrayGanador)
    {
    	boolean result = false;
    	
    	//IMPLEMENTACIÓN
    	
    	return result;
    }
    
    
}
