/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Mastermind.y;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class CInfoJuegoTest {
    @Test public void testColorExiste() {
        CInfoJuego Inf = new CInfoJuego();
        String[] arrayG = {"rojo", "azul", "verde", "amarillo", "negro"};
        boolean res_verde = Inf.colorExiste("verde", arrayG);
		assertEquals(res_verde,false);
    }
    
    @Test public void testJugadorAcierta() {
        CInfoJuego Inf = new CInfoJuego();
        String[] arrayU = {"rojo", "azul", "verde", "amarillo", "negro"};
        String[] arrayG = {"rojo", "azul", "verde", "amarillo", "negro"};
        String[] res_Win = Inf.comprobaciones(arrayU, arrayG);
        String[] expectedResult = {"negra","negra","negra","negra","negra"};
        assertArrayEquals(res_Win, expectedResult);
    }
}
